### ISSUE TITLE
--safe seems to break sized types

### ISSUE THREAD

**Issue by freebroccolo** [freebroccolo/agda-infinity-categories#2]
I've removed `--safe` because it causes termination checking to fail for some of the coinductive stuff, as it seems to disable the size machinery. This might be due to a recent change upstream. Should verify.

**Comment by potato4444** [comment]
As noted in the [user maual](https://agda.readthedocs.io/en/v2.6.0.1/language/safe-agda.html) `--safe` turns off `--sized-types` and `--guardedness` because they have a known proof of false when combined. You can turn back on either `--sized-types` or `--guardedness`, but not both .

So sticking `{-# OPTIONS --no-eta-equality --without-K --safe --sized-types #-}` at the top of the files should work.
